/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: BirdChen (https://sketchfab.com/bird219)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/human-head-926ba74256cf463c920afc1fdc8bc6ae
Title: Human Head
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/scene-2.glb')
  
  useEffect(() => {
    if (props.item && props.item.color) {
      // Apply the color to all mesh materials
      Object.values(materials).forEach(material => {
        material.color = new THREE.Color(props.item.color[0])
        material.needsUpdate = true
      })
    }
  }, [props.item, materials])
    
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.00258878, 2.27899384, -0.05075836]}
        rotation={[Math.PI / 2, 0, 0.22679036]}
        scale={0.2487698}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials['Scene_-_Root']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials['Scene_-_Root']}
        />
      </group>
    </group>
  );
}

export default Model;

useGLTF.preload("/models/scene-2.glb");